### ISSUE TITLE
empty .gosymtab for cgo builds

### ISSUE THREAD

**Issue by tgulacsi** [FiloSottile/gorebuild#3]
For a minimal example, see the attached
[cgo.zip](https://github.com/FiloSottile/gorebuild/files/333464/cgo.zip)

**Comment by tgulacsi** [comment]
I've asked for help at https://groups.google.com/forum/#!topic/golang-nuts/7PIDQtjMOUE

**Comment by dmitshur** [comment]
I can't reproduce on OS X.

What operating system are you using? What do `go version` and `go env` print for you?

**Comment by tgulacsi** [comment]
Go 1.6, Linux 64 bit, kernel 4.5
More precise answer will come next week

Dmitri Shuralyov notifications@github.com ezt írta (időpont: 2016. aug.
4., Cs 8:06):

**Comment by dmitshur** [comment]
Thanks, no need for more details because I can reproduce it on Linux with cgo binaries.

Ian's answer on https://groups.google.com/forum/#!topic/golang-nuts/7PIDQtjMOUE makes sense:

> [.gosymtab section] is currently always empty.  When using external linking, as when building a program that uses cgo, it gets dropped.  But even when it remains in the file, it is empty.  I don't think gosymtab has had any contents since the 1.2 release.
> 
> Just change it so that it doesn't care if there is no .gosymtab section, and to treat a missing .gosymtab section as an empty one.
