### ISSUE TITLE
add -all to rebuild everything under $GOPATH/bin

### ISSUE THREAD

**Issue by rakyll** [FiloSottile/gorebuild#6]
It would be nice to have an option such as -all to rebuild all binaries underneath $GOPATH/bin if anything is outdated.

**Comment by kisielk** [comment]
It already does that if you run just `gorebuild` without arguments. I submitted #5 to fix a problem though.

**Comment by rakyll** [comment]
Aha, nice! I came across to https://github.com/FiloSottile/gorebuild/pull/5 and didn't look further. Closing this non-issue issue :)

**Comment by FiloSottile** [comment]
Hey, this was easy ;)
